sudo: required language: node_js
node_js:
    - "stable"
    
services: 
    - docker
before_install: 
    - docker build -t circleci/argocd -f Dockerfile.dev .script:     
    - docker run -e CI=true jaysalpatel/circleci-argocd npm run test -- --coverage