version: 2
jobs:
  build:
    docker: #  circleci/node:10.0.0 # the primary container, where your job's commands are run
        - image: circleci/node:10.0.0  # run in the background
    steps:
      - checkout # check out the code in the project directory
      - run: npm install 
      - run: npm start
      - run: |
         echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_USERNAME --password-stdin
         docker run -d --name db company/proprietary-db:1.2.3

     # build the application image
     - run: docker build -t jaysalpatel/circleci-argocd .

     # deploy the image
     - run: docker push jaysalpatel/circleci-argocd
    
