version: 2
  jobs:
    test:
      docker: 
        - image: circleci/node
      steps:
        - checkout 
        - run: echo "running tests with npm"
        - run: npm install
        - run: npm test
    build:
      docker: 
        - image: circleci/node
      steps:
        - checkout
        - run: echo "running builds"
        - run: npm install
        - run: npm run build

workflows:
  version: 2
    test_build:
      jobs:
        - test
        - build
          requires:  
            - test