version: 2
jobs:
  test:
    machine:
      image: circleci/node:8.9
      docker_layer_caching: false
    working_directory: ~/repo
          
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            sudo yum update -y 
            npm install react-router-dom react-mdl 
          

  build:
  
    machine:
      image: circleci/node:8.9
      docker_layer_caching: false
    working_directory: ~/repo
          
    steps:
      - checkout 
      - run:
          name: build image
          command: |
            docker build -t $DOCKERHUB_USERNAME/circleci-argocd .
 
  push:
    machine:
      image: circleci/node:2.0
      
    working_directory: ~/circleci-argocd
    steps:
      - checkout 
      - run:
          name: Push image
          command: |
            docker build -t $DOCKERHUB_USERNAME/circleci-argocd .
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/circleci-argocd

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          context: DOCKERHUB
          filters:
            branches:
              only: master       
      - build:
          context: DOCKERHUB 
          requires:
            - test
          filters:
            branches:
              only: master
      - push:
          context: DOCKERHUB
          requires:
            - build
          filters:
            branches:
              only: master