version: 2
jobs:
  build:
    docker: #  circleci/node:10.0.0 # the primary container, where your job's commands are run
        - image: circleci/node:10.0.0  # run in the background
    steps:
      - checkout # check out the code in the project directory
      - run: npm install 
      - run: npm start
      - run: docker build -t circleci-argocd:latest . 
      - run: docker tag circleci-argocd:latest jaysalpatel/circle-argocd:latest
      - run: docker push jaysalpatel/circleci-argocd:latest
  

    
