name: Docker Push

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Docker Build & Push to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "jaysalpatel/circleci-argocd"
          TAG_NAME: "v0.0.2"
          LATEST: "true"

      - name: Docker Build & Push to AWS ECR
        uses: opspresso/action-docker@master
        with:
          args: --ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          IMAGE_URI: "536510685689.dkr.ecr.us-east-1.amazonaws.com/circleci-argocd"
          DOCKERFILE: "Dockerfile"
          TAG_NAME: "v0.0.1"
          LATEST: "true"